categories:
  food_recipes:
    label: 'Food Recipes'
  food_recipes.detail:
    label: 'Detail page'
    parent: food_recipes
  food_recipes.detail.stepImage:
    label: 'Image (Step)'
    parent: food_recipes.detail
  food_recipes.list:
    label: 'List view'
    parent: food_recipes
  food_recipes.list.image:
    label: 'Image (List)'
    parent: food_recipes.list

settings:
  food_recipes.detail.stepImage.width:
      label: 'Width'
      default: '765c'
      type: string
      category: food_recipes.detail.stepImage
  food_recipes.detail.affiliateImage.width:
      label: 'Width'
      default: '150c'
      type: string
      category: food_recipes.detail.stepImage
  food_recipes.list.image.width:
      label: 'Width'
      default: '576c'
      type: string
      category: food_recipes.list.image
  food_recipes.list.image.height:
      label: 'Height'
      default: ''
      type: string
      category: food_recipes.list.image
